console.log('1. Starting imports');
import { config } from './config.js';
console.log('Imported config');
import { createApp } from './server.js';
console.log('Imported server');
import { initSchema } from './db.js';
console.log('Imported db');
import { seed } from './seed.js';
console.log('Imported seed');
import { router as authRouter } from './routes/auth.js';
console.log('Imported authRouter');
import { router as profilesRouter } from './routes/profiles.js';
console.log('Imported profilesRouter');
import { router as reelsRouter } from './routes/reels.js';
console.log('Imported reelsRouter');
import { router as creatorsRouter } from './routes/creators.js';
console.log('Imported creatorsRouter');
import { router as moviesRouter } from './routes/movies.js';
console.log('Imported moviesRouter');
import { router as newsRouter } from './routes/news.js';
console.log('Imported newsRouter');
import { router as watchlistRouter } from './routes/watchlist.js';
console.log('Imported watchlistRouter');
import { router as streamsRouter } from './routes/streams.js';
console.log('Imported streamsRouter');
import { router as commentsRouter } from './routes/comments.js';
console.log('Imported commentsRouter');
import { router as notificationsRouter } from './routes/notifications.js';
console.log('Imported notificationsRouter');
import { router as recommendationsRouter } from './routes/recommendations.js';
console.log('Imported recommendationsRouter');
import { subscribe, userFromToken } from './events.js';
console.log('Imported events');

console.log('Calling initSchema...');
initSchema();
console.log('Schema initialized');
console.log('Calling seed...');
const seedResult = seed();
console.log('Seed result:', seedResult);
